# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8d61443f7cef296167de97869187b8d11c162a24c8efbb4c2f367f9e06ec66c554761149a83486fd0eb84380c16b304c03d24c5a68fd284d20048d5b7d23b0

test:
  secret_key_base: b7d698fe7eeb4c0e8d90432d655819051d7599b1c881af66a04f713daf69da16b80b90698f39f6135c02b39582b44843b9578d8f1cd1a8d8b44347a0eaa02e13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
